// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
var aws_app_analytics = 'enable';
var aws_cognito_identity_pool_id = 'us-east-2:b89bc642-716c-4a30-ae96-757153309235';
var aws_cognito_region = 'us-east-2';
var aws_mandatory_sign_in = 'enable';
var aws_mobile_analytics_app_id = 'cf1523bd6225474f83b65e8de3d58fc7';
var aws_mobile_analytics_app_region = 'us-east-1';
var aws_project_id = '82289ade-dfd3-4e73-b9e8-d5ee6fffbcd0';
var aws_project_name = 'KeyMe';
var aws_project_region = 'us-east-2';
var aws_resource_name_prefix = 'keyme-mobilehub-10968841';
var aws_sign_in_enabled = 'enable';
var aws_user_pools = 'enable';
var aws_user_pools_id = 'us-east-2_5iVkzZQ6o';
var aws_user_pools_mfa_type = 'OFF';
var aws_user_pools_web_client_id = '4i8en43f9otdtmf7cn5sluik05';

AWS.config.region = aws_project_region;
AWS.config.credentials = new AWS.CognitoIdentityCredentials({
    IdentityPoolId: aws_cognito_identity_pool_id
  }, {
    region: aws_cognito_region
  });
AWS.config.update({customUserAgent: 'MobileHub v0.1'});
