// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-2:b89bc642-716c-4a30-ae96-757153309235',
    'aws_cognito_region': 'us-east-2',
    'aws_mandatory_sign_in': 'enable',
    'aws_mobile_analytics_app_id': 'cf1523bd6225474f83b65e8de3d58fc7',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '82289ade-dfd3-4e73-b9e8-d5ee6fffbcd0',
    'aws_project_name': 'KeyMe',
    'aws_project_region': 'us-east-2',
    'aws_resource_name_prefix': 'keyme-mobilehub-10968841',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-2_5iVkzZQ6o',
    'aws_user_pools_mfa_type': 'OFF',
    'aws_user_pools_web_client_id': '4i8en43f9otdtmf7cn5sluik05',
}

export default awsmobile;
